
input_jsonl: example/test.jsonl

output_base_dir: exp/example_jwyu_jsonl
intermediate_scp_dir: ${output_base_dir}/intermediate
output_dir: ${output_base_dir}/final_output

songformer_init_args:
  model: SongFormer
  config_path: SongFormer.yaml
  output_dir: ${intermediate_scp_dir}/songformer_output
  CHECKPOINT_PATH: ckpts/SongFormer.safetensors
  MUSICFM_HOME_PATH: ckpts/MusicFM
  MUQ_PATH: ckpts/MuQ-large-msd-iter

separator_init_args:
  model_type: bs_roformer
  config_path: thirdparty/music_Source_Separation_Training/configs/viperx/model_bs_roformer_ep_317_sdr_12.9755.yaml
  # start_check_point: thirdparty/music_Source_Separation_Training/ckpts/model_bs_roformer_ep_317_sdr_12.9755.ckpt
  start_check_point: ckpts/model_bs_roformer_ep_317_sdr_12.9755.ckpt
  extract_instrumental: true
  store_dir: ${intermediate_scp_dir}/separation_output

vad_init_args:
  output_dir: ${intermediate_scp_dir}/vad_output



# TASK
resume: true
do_songformer: true
do_separation: true
do_vad: true
