description: AutoPrepSongV2

target:
  service: sing
  # name: msrresrchlabbasic
  name: msrresrchbasicvc
  workspace_name: workspace_genai
  
environment:
  # image: pytorch:24.10-py3
  # image: pytorch:25.11-py3-amlt
  image: pytorch:25.11-py3-amlt-AutoPrepSongV2
  registry: workspacegenaiacr.azurecr.io
  setup:
  - sudo chmod -R 777 /usr/local/lib/python3.12/dist-packages/  # 添加这行
  # - sudo chmod -R 777 /usr/local/
  # - export PATH=$$PATH:/home/aiscuser/.local/bin
  # - sudo apt update
  # - pip install -r requirements.txt 
  # - pip uninstall flash-attn -y
  # - sudo apt-get install ffmpeg -y

code:
  local_dir: $CONFIG_DIR/../../../
  
storage:
  conversationhub:
    storage_account_name: conversationhub
    container_name: unilm
  conversationhubhot:
    storage_account_name: conversationhubhot
    container_name: unilm


jobs:
  - name: data_preprocessing_b4
    sku: 40G1-A100  #[#nodes]x [memory-size]G{#gpus} [gpu-types] [IB] [NVLink/xGMI] [CUDA]@[regions]
    # sla_tier: Premium
    # sla_tier: Standard
    sla_tier: Standard
    priority: High
    identity: managed
    process_count_per_node: 1
    command:
      # - sleep infinity
      - python3 scripts/autoprep_song_jwyu.py
        --config_path config/amlt_basic.yaml
        --data_yaml amlt_submit/data_yaml/luoxue_batch4.yaml
        --start_idx 31320
        --chunk_size 261
      - python3 scripts/autoprep_song_jwyu.py
        --config_path config/amlt_basic.yaml
        --data_yaml amlt_submit/data_yaml/luoxue_batch4.yaml
        --start_idx 31581
        --chunk_size 261
    tags: [Project_Name:Speech, Experiment:Speech_Processing]
    submit_args:
      env:
        NCCL_DEBUG: INFO
        MKL_NUM_THREADS: 1
        OMP_NUM_THREADS: 1
        MKL_SERVICE_FORCE_INTEL: 1

  - name: data_preprocessing_b5
    sku: 40G1-A100  #[#nodes]x [memory-size]G{#gpus} [gpu-types] [IB] [NVLink/xGMI] [CUDA]@[regions]
    # sla_tier: Premium
    # sla_tier: Standard
    sla_tier: Standard
    priority: High
    identity: managed
    process_count_per_node: 1
    command:
      # - sleep infinity
      - python3 scripts/autoprep_song_jwyu.py
        --config_path config/amlt_basic.yaml
        --data_yaml amlt_submit/data_yaml/luoxue_batch5.yaml
        --start_idx 10680
        --chunk_size 178
    tags: [Project_Name:Speech, Experiment:Speech_Processing]
    submit_args:
      env:
        NCCL_DEBUG: INFO
        MKL_NUM_THREADS: 1
        OMP_NUM_THREADS: 1
        MKL_SERVICE_FORCE_INTEL: 1